### PR TITLE
Encoding Creds with Double b64 Encoding

### PR DESCRIPTION
**Pull request by 0xInfection**
We have discussed this already. :)

### CODE REVIEW

**Comment by smellslikekeenspirit** [comment]
Great work my teacher

**Comment by 0xInfection** [comment]
Hqhqhqhq. Teacher??? :v

**Comment by smellslikekeenspirit** [comment]
Whatta work bro whatta work. Aag laga dega aag laga dega

**Comment by 0xInfection** [comment]
:v using library functions? :v :v

**Comment by smellslikekeenspirit** [comment]
YES

**Comment by sudoanand** [comment]
waah yaar

**Comment by s0md3v** [comment]
waah yaar

**Comment by Cryptoshade** [comment]
waah yaar

**Comment by smellslikekeenspirit** [comment]
chhi yaar

**Comment by Souhardya** [comment]
waah yaar

**Comment by devanshbatham** [comment]
Waah Yaar,

**Comment by smellslikekeenspirit** [comment]
go away people I'm just a very wholesome person

**Comment by Souhardya** [comment]
so much crypto much wow

**Comment by smellslikekeenspirit** [comment]
> go away people I'm just a very wholesome person (2)

**Comment by s0md3v** [comment]
@smellslikekeenspirit Did aapko koi nahi bol rha h. Hum us bnde ko jo badi badi repositories me pull requests pe comment krke apne front page pe pin krta h aur coochie k chakkar me bemtlb ki repositories me PR dalta h xD

**Comment by smellslikekeenspirit** [comment]
arre what is this internal issue
feels like I'm watching Josh movie

**Comment by Souhardya** [comment]
Listen dummy, cryptography is communicating through math, but linguistics jettisoned the structuralist framework for language decades ago because it limits interpretability - there is an infinite regression of precise discrimination available for analysis of communication, and assigning meaningful ciphers to even several segmental and auto-segmental levels, in the context of a wholly unknown and alien language system (where we have no foundation of shared linguistic structures nor do we even have a species-level compatibility), would be functionally impossible to any level of certainty for a cryptographic system. The results could be contradictory, and using only a cryptographic framework, we would have no way to evaluate which might or might not be functionally meaningful. Now, perhaps in the future, machine-learning algorithms may be able to do something approximating this, but not currently, and even then I would want a human minder to monitor the results before acting on them. And that human should absolutely not be a cryptographer, who would think in the structuralist STEM epistemology of an engineer, but rather a linguist, and I would go further and even say a historical linguist/dialect specialist or maybe even a sociolinguist, surprisingly, simply because they would have a greater awareness of just how loose things can get. We would need a meaningful ranking of possible conflicts, and a cryptographer wouldn't be able to systematically evaluate unknown schemas the way a linguist might, especially one with extensive fieldwork experience.

Languages are not ciphers. They appear to be for a frighteningly great depth, and so lead many dilettantes astray.

**Comment by smellslikekeenspirit** [comment]
7 years about right but seems like I knew bro longer then that. One thing I learned a long time ago was to never judge a book by its cover. All I use to hear was Montana dis Montana dat we both was in alternative school but the first conversation we had we clicked instantly and been my guy ever since. We both came a long way an got more to go so keep striving bro. I’m more proud of u then you even know ✊🏿❤️💯

**Comment by Souhardya** [comment]
> 
> 
> 7 years about right but seems like I knew bro longer then that. One thing I learned a long time ago was to never judge a book by its cover. All I use to hear was Montana dis Montana dat we both was in alternative school but the first conversation we had we clicked instantly and been my guy ever since. We both came a long way an got more to go so keep striving bro. I’m more proud of u then you even know ✊🏿❤️💯

mine is better kthnxbye

**Comment by smellslikekeenspirit** [comment]
> > 7 years about right but seems like I knew bro longer then that. One thing I learned a long time ago was to never judge a book by its cover. All I use to hear was Montana dis Montana dat we both was in alternative school but the first conversation we had we clicked instantly and been my guy ever since. We both came a long way an got more to go so keep striving bro. I’m more proud of u then you even know ✊🏿❤️💯
> 
> mine is better kthnxbye

gaandu

**Comment by s0md3v** [comment]
@Souhardya bhai kasam se maine nhi btaya isko ki tu gaand deta h

**Comment by Souhardya** [comment]
> 
> 
> @Souhardya bhai kasam se maine nhi btaya isko ki tu gaand deta h

I thought we were homies

**Comment by s0md3v** [comment]
@Souhardya Tune isi k saamne mera saath nhi diya tha, yaad aaya?

**Comment by vatsal1947** [comment]
You go girl. Nice code. Totally authentic. I like that. Wallah habbibi

**Comment by vatsal1947** [comment]
Wah wah

**Comment by developerkunal** [comment]
waah yaar

**Comment by ghost** [comment]
Waah yaar

**Comment by darkc0d37** [comment]
Waah yaar

**Comment by smellslikekeenspirit** [comment]
> Waah yaar

Vatsal was your last comment directed at me? Please fuck off with your assumptions.

**Pull request merged**
